#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include "parser_param_test.h"


INSTANTIATE_TEST_CASE_P(otherAndYourPetHitByOther, ParseTest,
    testing::Values(
        ExtendedDamageLineInfo("Sheila Marlene hit Predator Rogue for 461 points of melee damage.",
                               "Sheila Marlene",
                               "Predator Rogue",
                               "damage",
                               "melee",
                               461),
        ExtendedDamageLineInfo("Sgtcuddle hit Predator Rogue for 4302 points of Burst damage.",
                               "Sgtcuddle",
                               "Predator Rogue",
                               "damage",
                               "Burst",
                               4302),
        ExtendedDamageLineInfo("Sgtcuddle hit Predator Rogue for 4302 points of Burst damage.",
                               "Sgtcuddle",
                               "Predator Rogue",
                               "damage",
                               "Burst",
                               4302),
        ExtendedDamageLineInfo("Sgtcuddle hit Predator Rogue for 15000 points of Full Auto damage.",
                               "Sgtcuddle",
                               "Predator Rogue",
                               "damage",
                               "Full Auto",
                               15000),
        ExtendedDamageLineInfo("Balas's reflect shield hit Junebop for 161 points of damage.",
                               "Balas",
                               "Junebop",
                               "damage",
                               "reflect shield",
                               161),
        ExtendedDamageLineInfo("Letter hit Reet of Paradise for 1586 points of melee damage.Critical hit!",
                               "Letter",
                               "Reet of Paradise",
                               "damage",
                               "melee",
                               1586,
                               true),
        ExtendedDamageLineInfo("Cratdat hit Ensign - Ilari'Ra for 801 points of projectile damage. Glancing hit.",
                               "Cratdat",
                               "Ensign - Ilari'Ra",
                               "damage",
                               "projectile",
                               801,
                               false,
                               true),
        ExtendedDamageLineInfo("Someone absorbed 8198 points of energy damage.",
                               "Unknown",
                               "Someone",
                               "damage",
                               "energy",
                               8198),
        ExtendedDamageLineInfo("Something hit Addicted2 for 49 points of damage by reflect shield.",
                               "Unknown",
                               "Addicted2",
                               "damage",
                               "reflect shield",
                               49),
        ExtendedDamageLineInfo("Something hit Enfodruid for 1 points of damage by damage shield.",
                               "Unknown",
                               "Enfodruid",
                               "damage",
                               "damage shield",
                               1)));

